### ISSUE TITLE
NullPointerException when running against `ohcount` sources

### ISSUE THREAD

**Issue by Ocramius** [blackducksoftware/ohcount4j#14]
To reproduce:

``` sh
git@github.com:blackducksoftware/ohcount4j.git
git@github.com:blackducksoftware/ohcount.git
cd ohcount4j
gradle build
./ohcount4j ../ohcount
```

The last command will produce `Error - java.util.concurrent.ExecutionException: java.lang.NullPointerException`

**Comment by PDegenPortnoy** [comment]
Moving the project to archive status. Therefore, closing all issues.
