### ISSUE TITLE
add support for Kotlin programming language

### ISSUE THREAD

**Issue by bschineller** [blackducksoftware/ohcount4j#21]
add support for Kotlin programming language

**Comment by mpujari** [comment]
Added support for Kotin, its similar to Java/C style with PR #22 .

File extensions for Kotlin are "kt" and "kts" (@bschineller correct me over here).

**Comment by PDegenPortnoy** [comment]
It looks to us that Kotlin is the _only_ language that uses the .kt and .kts extensions, therefore no need for disambigution.  

However, the `ohcount4j -l` output does not include kotlin.  Therefore, some additional work is needed.

PR #22 would have added Kotlin support, but the branch from which that pull request was made has been deleted, so it looks like we need to extract that code set as a diff or a patch and apply it to a new branch off of master.

**Comment by PDegenPortnoy** [comment]
PR for Kotlin programming language has been merged.
