### ISSUE TITLE
Put built jars on Maven Central

### ISSUE THREAD

**Issue by khampson** [blackducksoftware/ohcount4j#24]
Integration with Gradle/Maven etc. will be much improved if ohcount4j can be a **Maven Central** dependency like most other Java libraries. Currently, the user has to build it him/herself and then upload it to a local artifactory instance, or hack their build.gradle (or Maven equivalent) to grab the built jar from somewhere.

**Comment by PDegenPortnoy** [comment]
Would Bintray or Artifactory also be acceptable deployment targets?

**Comment by PDegenPortnoy** [comment]
Reference for deploying Travis CI to Bintray: https://docs.travis-ci.com/user/deployment/bintray

**Comment by jgustie** [comment]
I just did this for bdio, I can get it set up for Ohcount4j as well. I would suggest that we first update the group ID from `commoncomp` to `ohcount4j`, as in `com.blackducksoftware.ohcount4j:ohcount4j:2.0.0-SNAPSHOT`. The `commoncomp` made sense in BitBucket, but not here; I like the convention of using the GitHub repo ID as the group ID.

**Comment by jgustie** [comment]
The Bintray package is linked to JCenter, so all we need to do is publish a release to get Ohcount4j into JCenter.

We need #34 to be fixed first, but then the process for creating a release is basically:
1. Commit and push a `gradle.properties` without a `-SNAPSHOT` version to `master`.
2. Wait for the Travis build to complete.
3. Commit and push a `gradle.properties` with the next `-SNAPSHOT` version to `master`.

**Comment by PDegenPortnoy** [comment]
#34 has been fixed with #35, so we are ready to continue this process.  Would the next version be "2.1.1"?

**Comment by mydimension** [comment]
i bumped the version to `2.1.0-SNAPSHOT`

`-SNAPSHOT` should always precede the version it's about to be
