### ISSUE TITLE
Import internal wiki pages into the github wiki

### ISSUE THREAD

**Issue by mydimension** [blackducksoftware/ohcount4j#31]
In the interest of transparency, import/convert all internal wiki pages regarding ohcount4j to the github wiki: https://github.com/blackducksoftware/ohcount4j/wiki

**Comment by mydimension** [comment]
https://github.com/blackducksoftware/ohcount4j/wiki/Ohcount4J-Open-Source-Management-Plan

**Comment by PDegenPortnoy** [comment]
Moving the project to archive status. Therefore, closing all issues.
