### ISSUE TITLE
travis deploy published multiple times (per jdk tested)

### ISSUE THREAD

**Issue by mydimension** [blackducksoftware/ohcount4j#34]
looking at https://oss.jfrog.org/artifactory/oss-snapshot-local/com/blackducksoftware/ohcount4j/ohcount4j/2.0.0-SNAPSHOT/

It appears that the first build under travis (https://travis-ci.org/blackducksoftware/ohcount4j/builds/140972358) published 3 snapshots.

The fix is one of:
1. pick and test under one jdk (easier, but we loose jdk version coverage)
2. only publish the result of one jdk test (harder, but we keep coverage)

**Comment by jgustie** [comment]
We could keep the matrix and look at `TRAVIS_JOB_NUMBER` ending with ".1"

**Comment by mydimension** [comment]
fixed by #35
