### ISSUE TITLE
deploy to bintray failed

### ISSUE THREAD

**Issue by mydimension** [blackducksoftware/ohcount4j#36]
see: https://travis-ci.org/blackducksoftware/ohcount4j/jobs/144903212#L211

```
> Could not create package 'bds/oss/ohcount4j': HTTP/1.1 400 Bad Request [message:Package for path 'bds/oss' was invalid. Package license is mandatory]
```

**Comment by jgustie** [comment]
I think I messed up the Bintray setup, we need to wait for Bintray to re-approve the package and we should be good to go.

**Comment by mydimension** [comment]
this has been fixed: https://bintray.com/bds/oss/ohcount4j/2.0.0
